import assert from "node:assert/strict";
import fs from "node:fs";

const src=fs.readFileSync(new URL("../src/idle-ngu-progression.js",import.meta.url),"utf8");
const adventure=fs.readFileSync(new URL("../src/idle-adventure-v47.js",import.meta.url),"utf8");
const runtime=fs.readFileSync(new URL("../src/idle-sqlite-runtime.js",import.meta.url),"utf8");

assert.ok(src.includes('META-V47-EARLYGAME-NGU'));
assert.ok(src.includes('IDLE_NGU_SAVE_SCHEMA = 47')||src.includes('IDLE_NGU_SAVE_SCHEMA=47'));
assert.ok(src.includes('bosses:17'));
assert.ok(src.includes('bosses:30'));
assert.ok(src.includes('bosses:37'));
assert.ok(src.includes('bosses:58'));
assert.ok(src.includes('IDLE_NGU_YGG_FRUITS'));
assert.ok(src.includes('IDLE_NGU_DIGGERS'));
assert.ok(src.includes('IDLE_NGU_NORMAL_CHALLENGES'));
assert.ok(src.includes('applyRebirthResetV56_'));
assert.ok(src.includes('challengeReset:true'));
assert.ok(src.includes('REBIRTH_INTERDITE_DEFI'));
assert.ok(src.includes('idleNguChallengeBonuses'));
assert.ok(src.includes('augmentationPowerMultiplier'));
assert.ok(src.includes('timeMachineGoldMultiplier'));
assert.ok(src.includes('diggerSlotBonus'));
assert.ok(src.includes('challengeBonuses: challengePermanentBonuses'));
assert.ok(src.includes('titanCooldownReductionMs:titanChallengeBonuses.titanRespawnReductionMs'));
assert.ok(src.includes('titanLootLevelBonus:titanChallengeBonuses.titanLootLevelBonus'));
assert.ok(adventure.includes('challengeRespawnReduction'));
assert.ok(adventure.includes('challengeTitanLootLevel'));
assert.ok(runtime.includes('applique.result.challengeReset'));
assert.ok(runtime.includes('rebirthBasicTrainingStateV411'));
assert.ok(runtime.includes('row[c.BOSS_VAINCUS-1]=0'));
assert.ok(src.includes('upgradeYggFruit'));
assert.ok(src.includes('toggleDigger'));
assert.ok(src.includes('idleNguTimeMachineGrossGoldPerSecond'));
assert.ok(src.includes('diggerDrainTotal'));
assert.ok(src.includes('createIdleAdventureStateV47'));
assert.ok(adventure.includes('ADVENTURE-V47-NGU-EARLY'));
assert.ok(adventure.includes('level:C(lv,0,MAX)'));
assert.ok(adventure.includes('completedSets'));
assert.ok(adventure.includes('itemList'));
assert.ok(adventure.includes('Tutorial Cube'));
assert.ok(!src.includes('Essence renaissance'));
assert.ok(!src.includes('niveauxGagnes'));

// V53: no second progression economy may remain callable or influence combat.
assert.ok(runtime.includes("SOREAL_IDLE_V53_LEGACY_SHOP_DISABLED"));
assert.ok(runtime.includes("const bonusBoutique = 0;"));
assert.ok(runtime.includes("niveau:1"));
assert.ok(runtime.includes("legacy:false"));
assert.ok(runtime.includes("boutiqueLegacyDesactivee:true"));
assert.ok(runtime.includes("legacyXpMigratedV54"));
assert.ok(runtime.includes("statsCombat.metaNgu.currencies.experience"));
assert.ok(runtime.includes("renaissanceNativeCountV54"));
const combatStart=runtime.indexOf("function statsCombatPrincipalSorealIdleV413_(");
const combatEnd=runtime.indexOf("function definitionBossSorealIdle_(",combatStart);
assert.ok(combatStart>=0&&combatEnd>combatStart);
const combatBody=runtime.slice(combatStart,combatEnd);
assert.ok(!combatBody.includes("bonusRenaissanceSorealIdle_("));
assert.ok(!combatBody.includes("bonusAmeliorationsSorealIdle_("));
const progressStart=runtime.indexOf("function appliquerProgressionEnergieSorealIdle_(");
const progressEnd=runtime.indexOf("\nfunction ",progressStart+"function appliquerProgressionEnergieSorealIdle_(".length);
assert.ok(progressStart>=0&&progressEnd>progressStart);
const progressBody=runtime.slice(progressStart,progressEnd);
assert.ok(progressBody.includes("let niveau = 1;"));
assert.ok(progressBody.includes("legacyXpMigratedV54"));
assert.ok(!progressBody.includes("niveau >=\n    niveauDeblocageFonctionSorealIdle_(\n      'combat_auto'"));
// V55: metaNgu is the only Energy generator/source of cap and speed.
assert.ok(progressBody.includes("SOREAL_IDLE_V55_NGU_ENERGY_SOURCE_OF_TRUTH"));
assert.ok(progressBody.includes("SOREAL_IDLE_V55_NO_LEGACY_ENERGY_TICKS"));
assert.ok(progressBody.includes("SOREAL_IDLE_V55_NO_LEGACY_OFFLINE_ENERGY"));
assert.ok(progressBody.includes("syncIdleNguState("));
assert.ok(progressBody.includes("idleNguResourceGenerationPerSecond("));
assert.ok(!progressBody.includes("bonusAmeliorationsSorealIdle_("));
assert.ok(!progressBody.includes("bonusRenaissanceSorealIdle_("));
assert.ok(!progressBody.includes("ORGANISATION_ENERGIE_MAX_PAR_NIVEAU"));
assert.ok(!progressBody.includes("calculerTicksEnergieSorealIdle_("));
assert.ok(!progressBody.includes("creerSimulateurEnergieHorsLigneSorealIdle_("));
console.log("SOREAL IDLE V47 source contract: OK");
